# fly.toml app configuration file generated for mp3-by-vineetbamania on 2026-06-24T08:20:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mp3-by-vineetbamania'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[env]
  LOG_LEVEL = 'info'
  NODE_ENV = 'production'
  PORT = '8787'
  TMP_DIR = '/tmp/yt-dlp-fork'

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
